export const purchaseList = [
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점>",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
];

export const reviewList = [
  {
    image: "/img/test-poster.png",
    title: "현대무용 <시차적 관점> 리뷰",
    start_at: "2023.01.15 (목) 오전 10:00",
    price: "무료",
    vistor_cnt: 100,
    space: "서울예술대학교 빨간대문",
  },
];
